#!/bin/bash

sudo apt-get install -y zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
chsh -s /bin/zsh
wget -q https://raw.githubusercontent.com/Will-Grindelwald/Environment-Init/master/Linux/.ljc_alias -P ~
echo "source ~/.ljc_alias" >> ~/.ljcrc
# autojump
sudo apt-get install -y autojump
# incr
mkdir -p ~/.oh-my-zsh/custom/plugins/incr
wget -q http://mimosa-pudica.net/src/incr-0.2.zsh -P ~/.oh-my-zsh/custom/plugins/incr/ -O incr.plugin.zsh
# zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# zsh-autosuggestions
git clone git://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# autoenv
git clone git://github.com/kennethreitz/autoenv.git ~/.autoenv
echo 'source ~/.autoenv/activate.sh' >> ~/.ljcrc
sed -i '/plugins=(git)/a\\nHIST_STAMPS="yyyy-mm-dd"\nENABLE_CORRECTION="true"\nCOMPLETION_WAITING_DOTS="true"\nsetopt HIST_IGNORE_DUPS' ~/.zshrc
sed -i '/source $ZSH\/oh-my-zsh.sh/a\\nsource ~/.ljcrc' ~/.zshrc
sed -i 's/plugins=(git)/plugins=(autojump incr zsh-syntax-highlighting zsh-autosuggestions autoenv colored-man-pages colorize cp extract git history history-substring-search rsync screen ssh-agent sudo web-search)/g' ~/.zshrc
wget -q https://raw.githubusercontent.com/Will-Grindelwald/Environment-Init/master/Zsh/ljc.zsh-theme -P ~/.oh-my-zsh/theme
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="ljc"' ~/.zshrc
echo "alias -s html='vim'
alias -s rb='vim'
alias -s py='vim'
alias -s js='vim'
alias -s c='vim'
alias -s java='vim'
alias -s txt='vim'
alias -s tar='x'
alias -s gz='x'
alias -s tgz='x'
alias -s bz2='x'
alias -s xz='x'
alias -s zip='x'
alias -s rar='x'" >> ~/.zshrc
# 可能要重启才行
# Wiki: https://github.com/robbyrussell/oh-my-zsh/wiki
# 要是使用 vim 命令补全有问题 1. rm ~/.zcom* 2. exec zsh 3. 重启终端
# 只要有提示 insecure directories, 运行 compaudit 找出 insecure directories, 然后去掉 组 的 写权限
# sudo -s 提示 insecure directories, chown -R root ~/.oh-my-zsh; chmod -R 755 ~/.oh-my-zsh
