#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Pure Win10 For Recovery" {
    insmod part_gpt
    insmod fat
    insmod search_fs_uuid
    insmod chain
    search --fs-uuid --set=root --hint-bios=hd0,gpt1 --hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1 96CA-551B
    chainloader /EFI/Microsoft/Boot1/bootmgfw.efi
}
# "Shutdown" 启动项
menuentry "System shutdown" {
    echo "System shutting down..."
    halt
}
# "Restart" 启动项
menuentry "System restart" {
    echo "System rebooting..."
    reboot
}
